"""Make post_questionnaire.article_id nullable

Revision ID: c7b38397535b
Revises: 947c1d30f383
Create Date: 2025-05-06 17:28:58.498569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b38397535b'
down_revision = '947c1d30f383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_questionnaire', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_questionnaire', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
